# Generated by Django 4.2.21 on 2025-05-09 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bestHotelApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='id',
        ),
        migrations.AlterField(
            model_name='city',
            name='code',
            field=models.CharField(help_text='Unique city code', max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='city',
            field=models.ForeignKey(db_column='city_code', on_delete=django.db.models.deletion.CASCADE, related_name='hotels', to='bestHotelApp.city'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='code',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
