# Generated by Django 4.2.21 on 2025-05-09 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bestHotelApp', '0002_remove_city_id_alter_city_code_alter_city_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='city',
            field=models.ForeignKey(db_column='city_code', on_delete=django.db.models.deletion.CASCADE, to='bestHotelApp.city'),
        ),
    ]
