# Generated by Django 4.2.21 on 2025-05-09 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bestHotelApp', '0003_alter_hotel_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='city',
            field=models.ForeignKey(db_column='city_code', on_delete=django.db.models.deletion.CASCADE, related_name='hotels', to='bestHotelApp.city'),
        ),
    ]
